// Fetch
export const FETCH_TODOS_STARTED = "FETCH_TODOS_STARTED";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";

// Add
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";
export const ADD_TODO_STARTED = "ADD_TODO_STARTED";

// Toggle
export const TOGGLE_TODO_STARTED = "TOGGLE_TODO_STARTED";
export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_FAILURE = "TOGGLE_TODO_FAILURE";
